name: Extract and Move Tar File

on:
  # Run the workflow when a new file is uploaded to the bin folder
  push:
    paths:
      - 'bin/*.tgz'  # Watch for changes in the bin folder with tar.gz files

jobs:
  extract_and_move:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Tgz file
        run: |
         mkdir temp
         tar -xzf bin/*.tgz -C temp
         git mv temp/* source/
         rm -rf temp

      - name: Commit changes
        run: |
          git config --local user.email "partha09.com@gmail.com"
          git config --local user.name "partha_nm"
          git add .
          git commit -m "Extracted and moved tar file contents"
          git push origin main  # Push changes to the main branch
